### ISSUE TITLE
NSPasteboardType 类型的全局声明问题

### ISSUE THREAD

**Issue by arvinxx** [sketch-community/cocoascript-types#1]
拿这个方法测试了下 ([来源](https://sketchplugins.com/d/1373-setting-string-in-nspasteboard))：
```ts
/**
 * 获取粘贴文本
 **/
export const getTextFromClipboard = (): string => {
  const pasteboard = NSPasteboard.generalPasteboard();
  return pasteboard.stringForType(NSPasteboardTypeString).toString();
};
```
目前类型提示会报错。

![image](https://user-images.githubusercontent.com/28616219/101869248-f5936c00-3bb9-11eb-8e5a-ae7d67018db6.png)

`NSPasteboard` 的 `stringForType` 传入的是 `NSPasteboardType` 类型。

虽然在[文档](https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc)里面 `NSPasteboardType` 的类型是 `NSString`，但是其实它是有合法值的，例如 `NSPasteboardTypeURL`、`NSPasteboardTypeString`、`NSPasteboardTypePNG` 等。而这些合法值应该都是在 Cocoa 环境中直接全局定义过了的。

因此需要在全局声明 NSPasteboardTypeString 等变量才行。

![image](https://user-images.githubusercontent.com/28616219/101869851-5ff8dc00-3bbb-11eb-9ad4-e6772bace5a0.png)

这样就不会报错了
![image](https://user-images.githubusercontent.com/28616219/101869861-65eebd00-3bbb-11eb-8a1e-cbf72a0fde51.png)

以及以此类推的话，是不是所有 Type Alias 相关的合法变量都要在全局声明一遍？

**Comment by arvinxx** [comment]
对了 另外自动生成的文件是不是少了个点？

nspasteboardd.ts -> nspasteboard.d.ts

**Comment by yesmeck** [comment]
> 对了 另外自动生成的文件是不是少了个点？
> 
> nspasteboardd.ts -> nspasteboard.d.ts

修正了
