### ISSUE TITLE
 所有 set 类方法丢失入参类型

### ISSUE THREAD

**Issue by arvinxx** [sketch-community/cocoascript-types#6]
![image](https://user-images.githubusercontent.com/28616219/102710010-460d7680-42ea-11eb-8f58-26c31bb63dcc.png)

错误如上

![image](https://user-images.githubusercontent.com/28616219/102709998-3857f100-42ea-11eb-8d9f-c7d07fb4e513.png)

以及每个对象应该是支持采用 get 和 set 的取值和赋值方法的。

即： 

取值时可以使用
```
t = xxx.title()
```
 或者
```
t = xxx.title
```

赋值时使用
```
xxx.setTitle('Title') 
```
也应该支持下述的写法

```
xxx.title = "Title"
```

但是这样是不是目前 Typescript 不支持同时具有 get、set方法和同名的函数方法？

**Comment by yesmeck** [comment]
> 但是这样是不是目前 Typescript 不支持同时具有 get、set方法和同名的函数方法？

对的，这种没法支持。
